baseURL = "https://tmaiaroto.github.io/aegis/"
languageCode = "en-us"
title = "Aegis: An AWS Serverless Framework for Golang "
theme = "docuapi"
sectionPagesMenu = "main"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true


[params]
search = true

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "DocuAPI Example Site"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"<a class='github-link' href='https://github.com/tmaiaroto/aegis' target='_blank' title='Aegis on GitHub'><i class='fab fa-github'></i> Aegis on GitHub</a>",
"<div class='hugo-theme-credit'>Hugo Theme by <a href='https://github.com/bep' target='_blank'>bep</a></div>"
]

[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true

[menu]

  [[menu.main]]
    identifier = "routers"
    name = "Routers"
    title = "Aegis Routers"
    url = "/routers/"
    weight = -110

  [[menu.main]]
    identifier = "handler-dependencies"
    name = "Dependencies"
    title = "Aegis Dependencies"
    url = "/handler-dependencies/"
    weight = -100

  [[menu.main]]
    identifier = "helpers"
    name = "Helpers"
    title = "Aegis Helpers"
    url = "/helpers/"
    weight = -90

  [[menu.main]]
    identifier = "cli"
    name = "CLI"
    title = "Aegis Command Line Interface"
    url = "/cli/"
    weight = -80